#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : google-reauth
Version  : 0.1.0
Release  : 2
URL      : https://files.pythonhosted.org/packages/88/a9/68e764f071560fc947ce23944b10b2d7e8dc4ae0cf853565ef4e1e47f69e/google-reauth-0.1.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/88/a9/68e764f071560fc947ce23944b10b2d7e8dc4ae0cf853565ef4e1e47f69e/google-reauth-0.1.0.tar.gz
Summary  : Google Reauth Library
Group    : Development/Tools
License  : Apache-2.0
Requires: google-reauth-python3
Requires: google-reauth-license
Requires: google-reauth-python
Requires: oauth2client
BuildRequires : buildreq-distutils3

%description
============================
        
        |build| |docs| |pypi|
        
        This library provides Reauth support to Google's authentication libraries for
        Python. Reauth allows using two-factor authentication for end-user credentials.

%package license
Summary: license components for the google-reauth package.
Group: Default

%description license
license components for the google-reauth package.


%package python
Summary: python components for the google-reauth package.
Group: Default
Requires: google-reauth-python3

%description python
python components for the google-reauth package.


%package python3
Summary: python3 components for the google-reauth package.
Group: Default
Requires: python3-core

%description python3
python3 components for the google-reauth package.


%prep
%setup -q -n google-reauth-0.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1536549987
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/google-reauth
cp LICENSE %{buildroot}/usr/share/doc/google-reauth/LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/google-reauth/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
